### ISSUE TITLE
Text rendering in SVG costumes is off

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-render#215]
https://llk.github.io/scratch-gui/develop/compatibility-testing.html#10015857
![image](https://user-images.githubusercontent.com/654102/33996058-fb1e2238-e0ad-11e7-968e-d3ca3da7cafc.png)

**Comment by thisandagain** [comment]
Putting in February milestone as this is a blocker for importing SB2 projects.

**Comment by paulkaplan** [comment]
https://scratch.mit.edu/projects/214125084/#editor

**Comment by fsih** [comment]
Issues here
- When font size is not provided, scratch 2 assumes a different font size than scratch 3
- Leading when not set is also off
- Scratch 2 makes all text helvetica bold
   - We're not able to ship helvetica anymore (it came with Flash but we don't have the license to distribute it)
- Scratch svg renderer needs to be run on the thumbnail SVG

**Comment by thisandagain** [comment]
Assigning to @paulkaplan for next month to work on normalizing the "default" behavior between 2.0 and 3.0.

/cc @carljbowman @fsih @cwillisf

**Comment by BryceLTaylor** [comment]
Is this project:
https://llk.github.io/scratch-gui/develop/compatibility-testing.html#238467189
related to this issue?

**Comment by fsih** [comment]
@BryceLTaylor not sure what difference your link is demonstrating?

In response to my comment on April 4, here is what has been dealt with:
[ ] When font size is not provided, scratch 2 assumes a different font size than scratch 3
 - The 2.0 project is not providing any font size on the text element, and the SvgRenderer in scratch 3 is checking for text with no font size assigned and assigning it a size of 14. It seems like that default size is wrong. Text made in Scratch 2 is usually exported with a font size of 22 so I would try 22.
[x] Leading when not set is also off (multiline is shifted slightly down?)
- This should have been fixed by Paul's change https://github.com/LLK/paper.js/pull/7/files
[x] Scratch 2 makes all text helvetica bold
- We're not able to ship helvetica anymore (it came with Flash but it doesn't come with all browsers and we don't have the license to distribute it), so it's a known and intentional change that all helvetica should switch to noto medium and will look slightly different.
[x] Scratch svg renderer needs to be run on the thumbnail SVG
- Now filed as its own issue at https://github.com/LLK/scratch-gui/issues/2762

So I think all that's left to do here is change the default font size in SvgRenderer in the scratch-svg-renderer repo

**Comment by BryceLTaylor** [comment]
I made the project in 2.0 and drew lines close to the ends of each word.  in 3.0 there is a space between the end of the text and the lines.  I made it to show that the fonts when imported into 3.0 won't line up with other objects in the same image.

I'm seeing this as a really common incompatibility issue in the projects in the top 1000.

**Comment by kchadha** [comment]
@BryceLTaylor, they look pretty similar to me...

![image](https://user-images.githubusercontent.com/1786240/43905241-a6f3f06c-9bbe-11e8-847f-c163fb44cf32.png)

**Comment by fsih** [comment]
@BryceLTaylor that is a known and intentional incompatibility between Scratch 2.0 and 3.0. Many of the old fonts don't have open licenses, so we can't distribute them ourselves. Also, many of the old fonts support a very narrow, English-centric set of characters, so we wanted to change the fonts to be more international (at least covering Latin languages). We chose all of the fonts to be narrower than the old fonts so that it would hopefully cause fewer incompatibility issues, but let me know if you've seen any projects where the font change makes it seem really broken.

@kchadha I got confused by this too; I think you have to press space to switch to vector text. Only vector preserves the text editing capabilities.

**Comment by kchadha** [comment]
Ohhhhh! @fsih thank you for the clarification. =D

**Comment by LiFaytheGoblin** [comment]
Not 100% this is related, it might be a new issue, @kchadha: When converting a project from 2 to 3, multiple newlines and multiple blank spaces do not get respected.

To reproduce, go to the following project and click on options
https://llk.github.io/scratch-gui/develop/compatibility-testing.html#71789076

**Comment by fsih** [comment]
@LiFaytheGoblin that might be https://github.com/LLK/scratch-render/issues/292
