### ISSUE TITLE
Fullscreen stage is blurry

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-render#256]
I think a few similar issues were closed, but this one is specifically that when on the GUI and going into "fullscreen" mode, the rasterization scale of vector sprites does not change so they look blurry. 

This looks like the same issue, but was closed by the submitter when other svg re-rasterization was merged. https://github.com/LLK/scratch-gui/issues/1041

I think we may want to integrate the ratio of the `nativeSize` (really, scratch coordinate size) and the gl.canvas size into the scale we pass to the SVG renderer. Basically the ratio of nativeSize / gl.canvas size acts in a similar way to "devicePixelRatio", and should be treated like that.

Thoughts @cwillisf?

**Comment by cwillisf** [comment]
Yeah - that sounds good to me. It's a little bit tricky since various parts of the system (render, GUI, VM) need to know relative ratios for physical display pixels, logical display "pixels" (on high DPI displays), Scratch coordinates, and mouse coordinates, but as long as we can do all the necessary conversions I don't have a problem with combining two scaling factors into one variable like you're suggesting.
