### ISSUE TITLE
 Poor quality of vector images in full screen mode

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-render#334]
### Expected Behavior

Good anti-aliasing

### Actual Behavior

Incorrect anti-aliasing

### Steps to Reproduce

1.Open Scratch 3.0
2.Click on full screen

![x](https://user-images.githubusercontent.com/28606130/43994373-8e3fda1c-9da4-11e8-8682-8419c601f39f.png)

### Operating System and Browser

Windows 10, Chrome v.68.0.3440.106

---
Moved from LLK/scratch-gui#2847
/cc @SimaKyr

**Comment by thisandagain** [comment]
@cwillisf This is one of the top pieces of feedback we are seeing in the forums. Let's discuss next week. 

/cc @fsih @kchadha @BryceLTaylor @rschamp

**Comment by BryceLTaylor** [comment]
Her's a great repro of this from the community:
https://llk.github.io/scratch-gui/develop/compatibility-testing.html#230352473

It stamps a white sprite on a white background.  I bet it's not actually a problem with the stamping itself, but with the image itself.

**Comment by fsih** [comment]
@BryceLTaylor I think that might be https://github.com/LLK/scratch-render/issues/237 , not sure if it's the same issue

**Comment by BryceLTaylor** [comment]
@fsih It does seem that it is, I didn't know about the other issue.  They do seem related in that they have to do with aliasing.

**Comment by adroitwhiz** [comment]
I really hope this will be fixed before release. I hopped on Scratch 2.0 as soon as the public beta was available, but the terrible vector rendering artifacts (along with the block size issue) are why I haven't done the same with 3.0 and am hanging on to 2.0 for dear life.

Vector sprite quality as it stands is unacceptable. Between this bug, #246, #237, and #233, the vector rendering pipeline feels worse than half-baked and in desperate need of an overhaul in my opinion.

**Comment by ktbee** [comment]
Taking a look at this issue, it looks like currently [`getTexture`](https://github.com/LLK/scratch-render/blob/develop/src/SVGSkin.js#L68-L88) only scales textures up and doesn't have logic to scale textures back down again. What would y'all think about an approach where we instead generate textures at whichever scale we need (the first one starting at the sprite's saved size) and save them in an array in case we need them for later use?

Also aside from  `getTexture`, it looks like another codepath might be at play for when the texture is scaled up. I think we can use this same array of different sized textures to solve that issue as well.

/cc @fsih @cwillisf

**Comment by mzgoddard** [comment]
@cwillisf 

> I'm nervous that keeping independent textures at many different resolutions could occupy too much memory -- especially considering that (I believe) WebGL stores each texture in both CPU and GPU memory.

Do you know of any documentation discussing the textures being stored on CPU. CPUs have more memory available than GPUs. I think the GPU would run out before the CPU would take up enough to be problematic. Producing the various texture sizes on the CPU shouldn't cause extra memory usage on the GPU, right?

> Unfortunately in practice it's tricky to make mipmaps + texture filtering work well for all different scales, especially for images with crisp edges like the ones that tend to be popular in Scratch.

Can't we use [edge padding](http://wiki.polycount.com/wiki/Edge_padding) to create crisp edges? Instead of creating texture atlases we can still use the technique on two of the edges of each image.

I think you're implying one detail about mipmaps. To add clarity to that for other readers of this issue, WebGL 1 mipmaps only support power of two images. That means the width and height of each image has a value of 1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, etc. The vast majority of scratch costumes will not have power of two width and heights. So we will need to draw each image to a larger power of two image. Using an image for the source of the texture that has padding we will also need to use meshes with texture coordinates that account for the fact we are only drawing part of the image. (It is unlikely we can make use of the OpenGL extension that would do all this for us: https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_texture_non_power_of_two.txt)

I think producing the CPU "mipmaps" with different textures for each scale will be a small amount of javascript and require no API changes in scratch-render. Using GPU mipmaps will require work to produce some effect like edge padding and API changes to handle which mesh and its relevant texture coordinates to draw for a given texture.

Given that I think there may be a practical choice we might want to make here. I'm guessing either way we would eventually want to use mipmaps. Do we implement @ktbee's suggestion and mipmaps later or just wait to do mipmaps. It seems likely we need one of these to solve this specific bug.

**Comment by thisandagain** [comment]
Thanks @mzgoddard. I'm curious to get @cwillisf's feedback on this but my inclination would be to proceed with CPU "mipmaps" as long as we keep a close eye on performance through the implementation process.
