### ISSUE TITLE
Re-rasterization of a vector sprite at a higher resolution causes all others with the same costume to change to the high-resolution rasterization

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-render#374]
### Expected Behavior

A vector sprite's rendered appearance should be independent of the state of other instances of the sprite.

### Actual Behavior

When a vector sprite reaches a size that triggers its current costume's re-rasterization, other instances with the same costume (e.g. clones) will suddenly switch over to the re-rasterized costume regardless of _their_ size.

### Steps to Reproduce

- 1. Create a clone of a vector sprite.
- 2. Use the "set size" or "change size" blocks on one of the sprite instances, leaving the other at its original size.
- 3. When the resized instance's costume is re-rasterized, note the pixelation that occurs in the unchanged instance's costume.

You can test this with [this project](https://github.com/LLK/scratch-render/files/2649688/vector.sizing.demo.zip)-- just change the extension to a .sb3, click the green flag, and then press space. [In addition, here's a video of the bug.](https://youtu.be/0fug-56tLDA)

### Operating System and Browser

Fedora Workstation 29 x86_64, Chromium 70.0.3538.110

**Comment by ktbee** [comment]
After taking a look at this issue and chatting with @mzgoddard, it looks like this low resolution for the clone skin has the same root cause as https://github.com/LLK/scratch-render/issues/334. The skin is scaled up for the original sprite, but we don't currently have logic to scale down the same skin for the clone, so it's not shown at its original resolution. 

[As we were discussing in this and the following comments](https://github.com/LLK/scratch-render/issues/334#issuecomment-449143929), we could implement mipmaps/different skin resolutions using JavaScript or WebGL. Any thoughts on this now that we're revisiting it, @cwillisf ?
