### ISSUE TITLE
Variables, Lists and Ask dialog huge compatibility issues

### ISSUE THREAD

**Issue by JuegOStrower** [LLK/scratch-render#401]
### Expected Behavior
The above compatibility issues should be fixed.

### Actual Behavior
This causes differences between the Scratch 2.0 Player and the Scratch 3.0 one.
- [ ] The white doesn't seem good for variables a list, the light gray again would be nice.
- [ ] The vars have different sizes, so if a variable has to be in exactly one place, it'll disturb other part of the projects. It could happen to a variable to be over another one.
- [ ] Variables, lists and the ask input are always in front of any sprites. In scratch 2.0, using "send to front" on sprite put it in front of that. This was used to "change" the ask dialog and the variables monitors for something that seems good in that project.

### Steps to Reproduce
Just create a variable, a list or ask something. Then, in a sprite click Send to Front. However, it's style behind the monitor/dialog. This didn't happen on Scratch 2.0.
About the size, you can see the difference on this project: https://scratch.mit.edu/projects/54080704/
About the color, light gray is just better.

### Operating System and Browser
Windows 10, Google Chrome

**Comment by towerofnix** [comment]
Potentially related to LLK/scratch-vm#1397 (which is required to fix your third point), although I doubt it's an issue they'll prioritize too soon.

**Comment by thisandagain** [comment]
We are tracking the third issue and would like to eventually move monitors into the rendering engine, but it is a large project and we have many other items that take priority. The other two items are intentional changes that we made after considerable discussion and testing. We realize that they are different from 2.0, but some of these differences we feel are a step in the right direction.
