### ISSUE TITLE
Touching color block not working

### ISSUE THREAD

**Issue by peabrainiac** [LLK/scratch-render#422]
### Expected Behavior

The block should return true if the color is touched

### Actual Behavior

The block always returns false

### Steps to Reproduce

1. create a new scratch project
2. grab the <touching color [ ]>-block
3. set the color to the background color
4. run the block

### Operating System and Browser

Windows 10 + Firefox 65

**Comment by peabrainiac** [comment]
I also tested this on google chrome 72.0, and it doesn't seem to work there either.

**Comment by TheLogFather** [comment]
Scratch checks the bounding box of the backdrop, so if the backdrop is empty (which it is for the initial 0x0 vector backdrop of a new project) then it can't intersect the bounding box of any sprite's costume.

Draw something into the backdrop, and ensure that the bounding box of the vector backdrop now overlaps the sprite costume, and you'll find that touching white works fine. (But move the sprite outside that bounding box, but still entirely within the project area, and it'll show false again.)

This was also the same for Scratch 2 – the only complicating factor being that a new project would start with a bitmap backdrop filled with white, rather than an empty vector backdrop, meaning that in Scratch 2 you have to actually switch the backdrop to vector and then get rid of the white rect to make it behave the same as Scratch 3.

One interesting point here is that both Scratch 2 and Scratch 3 consider 'offscreen' (i.e. beyond the bounds of the project area) to be white when it come to touching tests. (Though note that vector costumes that extend offscreen can also be detected through touching colour, but not vector backdrops.)

**Comment by peabrainiac** [comment]
You're right, drawing something in the corner of the stage to makes the block return true again. I find that a little counterintuitive though - the backdrop is still transparent near the scratch cat, yet the block returns a different result because the bounding box has changed. Maybe this should be changed to something more intuitive?

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/2044
