### ISSUE TITLE
Some costumes flipped horizontally

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-render#95]
I'm not 100% sure if this is an issue in the rendering engine or the VM. Filing here for now pending investigation.

### Expected Behavior

When loading a project, costumes should be loaded in the rotation and orientation that they were created in.

### Actual Behavior

When loading a project, some costumes will be "flipped" horizontally.

### Steps to Reproduce

- https://scratch.mit.edu/projects/100736613/ (Original)
- https://llk.github.io/scratch-gui/#100736613 (3.0)

### Reference
![image](https://cloud.githubusercontent.com/assets/747641/22990192/5c47f28e-f386-11e6-9534-c6a2964d9941.png)

![image](https://cloud.githubusercontent.com/assets/747641/22990181/5873441a-f386-11e6-838e-b03782d38f3d.png)

### Operating System and Browser

Mac OS 10.12.2 Chrome Version 56.0.2924.87 (64-bit)

**Comment by SillyInventor** [comment]
This is caused by the leftRight rotation setting. I think something is amiss with the scratch 2.0 save json file, because according to the response text the image is set to direction -90 degrees (flipped), but in the scratch 2.0 version even though it has direction -90 only flips when calling a change to rotation or rotation-style. Bizarre.

**Comment by thisandagain** [comment]
Thanks for the investigation @SillyInventor ! Hmm ... this is a bit of a head scratcher. Moving to backlog as it feels like an edge case, but certainly is a compatibility concern.

**Comment by rschamp** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/519
